### ISSUE TITLE
button niet tabben

### ISSUE THREAD

**Issue by lisagjh** [Remy2072/the-startup-responsive-interactieve-website#3]
de knop met 'discover' is niet te tabben, verder is de toegankelijkheid goed (lighthouse 100%)

**Comment by KaanKalmi** [comment]
![image](https://github.com/Remy2072/the-startup-responsive-interactieve-website/assets/144000125/3fe56924-e480-4684-8588-5210d6b2c08c)

Het kan wel

**Comment by lisagjh** [comment]
Dan ligt het denk aan mijn browser, sorry!
