### ISSUE TITLE
light house test/toegankelijkheid

### ISSUE THREAD

**Issue by Ronabundy1** [Remy2072/the-startup-responsive-interactieve-website#7]
Als je de light house test bekijk, ziet alles uitstekend uit, Ga zo door!

<img width="851" alt="Schermafbeelding 2024-01-15 113441 toegangelijkheid R" src="https://github.com/Remy2072/the-startup-responsive-interactieve-website/assets/118179932/12d75f57-d2a6-4084-85b5-de86258530d1">

**Comment by krijnhoetmer** [comment]
@Ronabundy1 En wat als je via een handmatige test bijvoorbeeld alt attributen checkt?
